#! /usr/bin/python
# $Id: roundup-mailgw,v 1.2 2001-07-29 07:01:39 richard Exp $

import sys
if int(sys.version[0]) < 2:
    print "Roundup requires Python 2.0 or newer."
    sys.exit(1)

# figure the instance home
import os
if len(sys.argv) > 1:
    instance_home = sys.argv[1]
else:
    instance_home = os.environ.get('ROUNDUP_INSTANCE', '')
if not instance_home:
    print 'No instance home specified'
    sys.exit(1)

# get the instance
path, instance = os.path.split(instance_home)
sys.path.insert(0, path)
instance = __import__(instance)
sys.path[0]

# invokde the mail handler
db = instance.open('admin')
handler = instance.MailGW(db)
handler.main(sys.stdin)

#
# $Log: not supported by cvs2svn $
# Revision 1.1  2001/07/23 03:46:48  richard
# moving the bin files to facilitate out-of-the-boxness
#
# Revision 1.1  2001/07/22 11:15:45  richard
# More Grande Splite stuff
#
#
# vim: set filetype=python ts=4 sw=4 et si
