#! /usr/bin/env python
#
# Copyright (c) 2001 Richard Jones
# This module is free software, and you may redistribute it and/or modify
# under the same terms as Python, so long as this copyright message and
# disclaimer are retained in their original form.
#
# This module is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# $Id: run_tests,v 1.7 2002-05-29 01:16:16 richard Exp $

# make sure we have the htmlbase
try:
    from roundup.templates.classic import htmlbase
except ImportError:
    import setup
    setup.buildTemplates()

from test import go
import sys
if len(sys.argv) > 1:
    go(sys.argv[1:])
else:
    go()

#
# $Log: not supported by cvs2svn $
# Revision 1.6  2002/05/25 07:24:29  rochecompaan
# oops
#
# Revision 1.4  2002/02/14 23:38:12  richard
# Fixed the unit tests for the mailgw re: the x-roundup-name header.
# Also made the test runner more user-friendly:
#   ./run_tests            - detect all tests in test/test_<name>.py and run them
#   ./run_tests <name>     - run only test/test_<name>.py
# eg ./run_tests mailgw    - run the mailgw test from test/test_mailgw.py
#
# Revision 1.3  2002/01/23 20:09:41  jhermann
# Proper fix for failing test
#
# Revision 1.2  2002/01/23 11:08:52  grubert
#  . run_tests testReldate_date failed if LANG is 'german'
#
# Revision 1.1  2002/01/23 05:53:46  richard
# convenience script for running the unit tests...
# ... they are no longer run in the setup, since they take too long
#
#
#
#
# vim: set filetype=python ts=4 sw=4 et si
