#! /bin/sh

# if there are multiple trackers, d=demo t=tracker ...
# returns last one for testing that server is up. Does not test
# each tracker.
tracker=$(ps -ef | sed -ne '/roundup-server/s/^.*\s\(\w*\)=.*$/\1/p')
# Disable using of proxy
wget -q -O /dev/null --no-verbose --proxy off http://localhost:8080/${tracker:-demo}/
